language: ruby
cache: bundler

rvm:
  - 2.1.0

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - virtualstaticvoid@gmail.com
    on_failure: change
    on_success: never
